### ISSUE TITLE
bug: Error in terminal on first use

### ISSUE THREAD

**Issue by VorpalBlade** [quickemu-project/quickgui#217]
**I confirm this bug has not already been reported**
- [ ] I have searched the issues and this bug has not been reported previously

**Describe the bug**

```console
❯ ./quickgui-1.2.10+1-linux.AppImage
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): null is not a String or Directory
#0      _Directory.current= (dart:io/directory_impl.dart:56)
#1      Directory.current= (dart:io/directory.dart:174)
#2      _DownloaderMenuState.build.<anonymous closure>.<anonymous closure> (package:quickgui/src/widgets/home_page/downloader_menu.dart:61)
#3      State.setState (package:flutter/src/widgets/framework.dart:1203)
#4      _DownloaderMenuState.initState.<anonymous closure> (package:quickgui/src/widgets/home_page/downloader_menu.dart:24)
#5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:847)
#6      Future._propagateToListeners (dart:async/future_impl.dart:876)
#7      Future._completeWithValue (dart:async/future_impl.dart:652)
<asynchronous suspension>
```

**To Reproduce**
1. Install Quickemu from Arch Linux AUR
2. Download AppImage for Quickgui
3. Launch it for first time (never having used quickemu or quickgui before)
4. Click "Create new machines"
5. See error in terminal

**Expected behavior**
No error in terminal

**Desktop (please complete the following information):**
 - Quickgui Versdion: 1.2.10 (from AppImage)
 - OS: Arch Linux
 - Version: N/A (rolling release)

**Screenshots**

**Additional context**

**Comment by xylophoneengine** [comment]
I am experiencing the same issue with the current pre-built AppImage (quickgui-1.2.10+1-linux.appimage). Furthermore, I am unable to select the vm directory (management and creation dialogue).

Desktop (please complete the following information):

* Quickgui Version: 1.2.10+1 (from AppImage)
* OS: Kubuntu 
* Version: 24.04. LTS
* KDE Plasma 5.27.11 (Wayland)
