### ISSUE TITLE
bug: quickgui fails to build on NixOS

### ISSUE THREAD

**Issue by D1zzl3D0p** [quickemu-project/quickgui#237]
**I confirm this bug has not already been reported**
- [ x] I have searched the issues and this bug has not been reported previously

**Description**
When building/installing the package on NixOS, errors occur that halt the build process.

**To Reproduce**
add quickgui to `environment.systemPackages`
run `sudo nixos-rebuild switch`

**Expected behavior**
Successful Build

**Desktop:**
 - Quickgui Version: 1.2.10
 - OS: NixOS
 - Version: unstable

**Additional context**
Errors from build:
```
quickgui> [   +8 ms] FAILED: /build/source/linux/flutter/ephemeral/libflutter_linux_gtk.so /build/source/linux/flutter/ephemeral/flutter_linux/fl_basic_message_channel.h /build/source/linux/flutter/ephemeral/flutter_linux/fl_binary_codec.h /build/source/linux/flutter/ephemeral/flutter_linux/fl_binary_messenger.h /build/source/linux/flutter/ephemeral/flutter_linux/fl_dart_project.h /build/source/linux/flutter/ephemeral/flutter_linux/fl_engine.h /build/source/linux/flutter/ephemeral/flutter_linux/fl_json_message_codec.h /build/source/linux/flutter/ephemeral/flutter_linux/fl_json_method_codec.h /build/source/linux/flutter/ephemeral/flutter_linux/fl_message_codec.h /build/source/linux/flutter/ephemeral/flutter_linux/fl_method_call.h /build/source/linux/flutter/ephemeral/flutter_linux/fl_method_channel.h /build/source/linux/flutter/ephemeral/flutter_linux/fl_method_codec.h /build/source/linux/flutter/ephemeral/flutter_linux/fl_method_response.h /build/source/linux/flutter/ephemeral/flutter_linux/fl_plugin_registrar.h /build/source/linux/flutter/ephemeral/flutter_linux/fl_plugin_registry.h /build/source/linux/flutter/ephemeral/flutter_linux/fl_standard_message_codec.h /build/source/linux/flutter/ephemeral/flutter_linux/fl_standard_method_codec.h /build/source/linux/flutter/ephemeral/flutter_linux/fl_string_codec.h /build/source/linux/flutter/ephemeral/flutter_linux/fl_value.h /build/source/linux/flutter/ephemeral/flutter_linux/fl_view.h /build/source/linux/flutter/ephemeral/flutter_linux/flutter_linux.h flutter/_phony_ /build/source/build/linux/x64/release/flutter/_phony_ 

...

quickgui> [        ] [  +10 ms] Failed obtaining PRETTY_NAME for Linux: PathNotFoundException: Cannot open file, path = '/usr/lib/os-release' (OS Error: No such file or directory, errno = 2)

...

quickgui> [        ] [+4813 ms] /nix/store/bgvqb8pa4vspr3abxxyww7fdxqdqwmjr-flutter-sdk-flutter/lib/src/material/color_scheme.dart:1915:39: Error: Method not found: 'SchemeRainbow'.
quickgui> [        ] [   +4 ms]       DynamicSchemeVariant.rainbow => SchemeRainbow(sourceColorHct: sourceColor, isDark: isDark, contrastLevel: contrastLevel),
quickgui> [        ] [        ]                                       ^^^^^^^^^^^^^
quickgui> [        ] [        ] /nix/store/bgvqb8pa4vspr3abxxyww7fdxqdqwmjr-flutter-sdk-flutter/lib/src/material/color_scheme.dart:1916:42: Error: Method not found: 'SchemeFruitSalad'.
quickgui> [        ] [        ]       DynamicSchemeVariant.fruitSalad => SchemeFruitSalad(sourceColorHct: sourceColor, isDark: isDark, contrastLevel: contrastLevel),
quickgui> [        ] [        ]                                          ^^^^^^^^^^^^^^^^

```
Full logs from build:
```
quickgui> building '/nix/store/zyfgvki44wpdagcdmwc429ny2qn2h1p3-quickgui-1.2.10.drv'
quickgui> Running phase: unpackPhase
quickgui> unpacking source archive /nix/store/72igdr4x2jvjsv9jrhq1p42837svircm-source
quickgui> source root is source
quickgui> Running phase: patchPhase
quickgui> Running phase: updateAutotoolsGnuConfigScriptsPhase
quickgui> Running phase: configurePhase
quickgui> no configure script, doing nothing
quickgui> Executing dartConfigHook
quickgui> Setting up SDK
quickgui> Installing dependencies
quickgui> Finished dartConfigHook
quickgui> Running phase: buildPhase
quickgui> [  +14 ms] Failed obtaining PRETTY_NAME for Linux: PathNotFoundException: Cannot open file, path = '/usr/lib/os-release' (OS Error: No such file or directory, errno = 2)
quickgui> [  +16 ms] Unable to locate an Android SDK.
quickgui> [ +121 ms] Skipping pub get: generated by third-party.
quickgui> [  +59 ms] Found plugin url_launcher_web at /nix/store/02bwaa9svc88fyzbpffxic18475dzghl-pub-url_launcher_web-2.3.1/
quickgui> [  +43 ms] Found plugin window_size at /nix/store/281pj1qkmwsbzmn02r6q9icaj11x15ab-pub-window_size-0.1.0/plugins/window_size/
quickgui> [  +51 ms] Found plugin path_provider_linux at /nix/store/4k81c6xlrv9flldg38h9vz71yjynvbnn-pub-path_provider_linux-2.2.1/
quickgui> [  +28 ms] Found plugin shared_preferences_android at /nix/store/85nhyhivqhdfn8zcp59b4sxcz51nb4ja-pub-shared_preferences_android-2.2.3/
quickgui> [  +26 ms] Found plugin shared_preferences_foundation at /nix/store/aklaxr0m3qnidlyly2srv8jx4n28b3iz-pub-shared_preferences_foundation-2.4.0/
quickgui> [  +24 ms] Found plugin url_launcher_ios at /nix/store/c0y1cs8qg8iimamzm0y6g0nn7bz6l8cj-pub-url_launcher_ios-6.3.0/
quickgui> [  +14 ms] Found plugin flutter_plugin_android_lifecycle at /nix/store/fmpddwahgxhap1444frgg4vkd1nm0ic0-pub-flutter_plugin_android_lifecycle-2.0.20/
quickgui> [  +21 ms] Found plugin shared_preferences at /nix/store/iawy6vrk3vdj2q32pnqgf6amhp0dk3xh-pub-shared_preferences-2.2.3/
quickgui> [  +10 ms] Found plugin url_launcher_windows at /nix/store/ivk6fyy4sc5rm6xwq3rr2q3xicr4p5in-pub-url_launcher_windows-3.1.1/
quickgui> [  +28 ms] Found plugin url_launcher_android at /nix/store/ly3f4fiaspa5n4nak4sh23gxm6wdxr68-pub-url_launcher_android-6.3.3/
quickgui> [  +17 ms] Found plugin file_picker at /nix/store/nbksgwm99d12hkss1h768rx16jf7gx8h-pub-file_picker-8.0.6/
quickgui> [   +3 ms] Found plugin url_launcher_macos at /nix/store/nlrr9r5bzb9b1c82lhbx1n26db13ll5k-pub-url_launcher_macos-3.2.0/
quickgui> [   +6 ms] Found plugin shared_preferences_linux at /nix/store/pa9rc1ak6rpfbw7rnb3hn19385l0m6k5-pub-shared_preferences_linux-2.3.2/
quickgui> [   +6 ms] Found plugin shared_preferences_windows at /nix/store/qy21qcd19p1wwp1lb1nyj96sy81ag8js-pub-shared_preferences_windows-2.3.2/
quickgui> [  +12 ms] Found plugin path_provider_windows at /nix/store/wib0w6wj5clkiwglwfiddyiby1ssj6wk-pub-path_provider_windows-2.2.1/
quickgui> [   +3 ms] Found plugin url_launcher_linux at /nix/store/wrclapn89ya4jlcg654l0qwh6xlbw4l5-pub-url_launcher_linux-3.1.1/
quickgui> [   +7 ms] Found plugin package_info_plus at /nix/store/xqjqv966371lq9djmlrgmwkrsvf8wjsh-pub-package_info_plus-8.0.0/
quickgui> [   +6 ms] Found plugin url_launcher at /nix/store/yy83yg70as8yijm6vz1n633vv4fkjcaq-pub-url_launcher-6.3.0/
quickgui> [  +10 ms] Found plugin shared_preferences_web at /nix/store/zdjfqds2j65c0k1yqjx3dmy6xiqlci9h-pub-shared_preferences_web-2.3.0/
quickgui> [  +49 ms] Found plugin url_launcher_web at /nix/store/02bwaa9svc88fyzbpffxic18475dzghl-pub-url_launcher_web-2.3.1/
quickgui> [  +11 ms] Found plugin window_size at /nix/store/281pj1qkmwsbzmn02r6q9icaj11x15ab-pub-window_size-0.1.0/plugins/window_size/
quickgui> [  +14 ms] Found plugin path_provider_linux at /nix/store/4k81c6xlrv9flldg38h9vz71yjynvbnn-pub-path_provider_linux-2.2.1/
quickgui> [   +7 ms] Found plugin shared_preferences_android at /nix/store/85nhyhivqhdfn8zcp59b4sxcz51nb4ja-pub-shared_preferences_android-2.2.3/
quickgui> [   +7 ms] Found plugin shared_preferences_foundation at /nix/store/aklaxr0m3qnidlyly2srv8jx4n28b3iz-pub-shared_preferences_foundation-2.4.0/
quickgui> [   +6 ms] Found plugin url_launcher_ios at /nix/store/c0y1cs8qg8iimamzm0y6g0nn7bz6l8cj-pub-url_launcher_ios-6.3.0/
quickgui> [  +10 ms] Found plugin flutter_plugin_android_lifecycle at /nix/store/fmpddwahgxhap1444frgg4vkd1nm0ic0-pub-flutter_plugin_android_lifecycle-2.0.20/
quickgui> [   +6 ms] Found plugin shared_preferences at /nix/store/iawy6vrk3vdj2q32pnqgf6amhp0dk3xh-pub-shared_preferences-2.2.3/
quickgui> [   +1 ms] Found plugin url_launcher_windows at /nix/store/ivk6fyy4sc5rm6xwq3rr2q3xicr4p5in-pub-url_launcher_windows-3.1.1/
quickgui> [   +5 ms] Found plugin url_launcher_android at /nix/store/ly3f4fiaspa5n4nak4sh23gxm6wdxr68-pub-url_launcher_android-6.3.3/
quickgui> [   +4 ms] Found plugin file_picker at /nix/store/nbksgwm99d12hkss1h768rx16jf7gx8h-pub-file_picker-8.0.6/
quickgui> [   +1 ms] Found plugin url_launcher_macos at /nix/store/nlrr9r5bzb9b1c82lhbx1n26db13ll5k-pub-url_launcher_macos-3.2.0/
quickgui> [   +2 ms] Found plugin shared_preferences_linux at /nix/store/pa9rc1ak6rpfbw7rnb3hn19385l0m6k5-pub-shared_preferences_linux-2.3.2/
quickgui> [   +4 ms] Found plugin shared_preferences_windows at /nix/store/qy21qcd19p1wwp1lb1nyj96sy81ag8js-pub-shared_preferences_windows-2.3.2/
quickgui> [   +6 ms] Found plugin path_provider_windows at /nix/store/wib0w6wj5clkiwglwfiddyiby1ssj6wk-pub-path_provider_windows-2.2.1/
quickgui> [   +2 ms] Found plugin url_launcher_linux at /nix/store/wrclapn89ya4jlcg654l0qwh6xlbw4l5-pub-url_launcher_linux-3.1.1/
quickgui> [   +1 ms] Found plugin package_info_plus at /nix/store/xqjqv966371lq9djmlrgmwkrsvf8wjsh-pub-package_info_plus-8.0.0/
quickgui> [   +2 ms] Found plugin url_launcher at /nix/store/yy83yg70as8yijm6vz1n633vv4fkjcaq-pub-url_launcher-6.3.0/
quickgui> [   +3 ms] Found plugin shared_preferences_web at /nix/store/zdjfqds2j65c0k1yqjx3dmy6xiqlci9h-pub-shared_preferences_web-2.3.0/
quickgui> [  +61 ms] Building Linux application...
quickgui> [   +5 ms] executing: [build/linux/x64/release/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DFLUTTER_TARGET_PLATFORM=linux-x64 /build/source/linux
quickgui> [ +464 ms] -- The CXX compiler identification is Clang 18.1.8
quickgui> [ +113 ms] -- Detecting CXX compiler ABI info
quickgui> [ +439 ms] -- Detecting CXX compiler ABI info - done
quickgui> [ +122 ms] -- Check for working CXX compiler: /nix/store/qajfjv5lnfys2ykm0ggkr4lnnkvgs10r-clang-wrapper-18.1.8/bin/clang++ - skipped
quickgui> [        ] -- Detecting CXX compile features
quickgui> [   +1 ms] -- Detecting CXX compile features - done
quickgui> [  +10 ms] -- Found PkgConfig: /nix/store/946chn5ja4yrvnnc5izwv792cc57xpy8-pkg-config-wrapper-0.29.2/bin/pkg-config (found version "0.29.2")
quickgui> [        ] -- Checking for module 'gtk+-3.0'
quickgui> [  +64 ms] --   Found gtk+-3.0, version 3.24.43
quickgui> [ +477 ms] -- Checking for module 'glib-2.0'
quickgui> [  +51 ms] --   Found glib-2.0, version 2.82.1
quickgui> [  +90 ms] -- Checking for module 'gio-2.0'
quickgui> [  +38 ms] --   Found gio-2.0, version 2.82.1
quickgui> [ +176 ms] -- Configuring done (2.0s)
quickgui> [  +58 ms] -- Generating done (0.1s)
quickgui> [        ] -- Build files have been written to: /build/source/build/linux/x64/release
quickgui> [  +10 ms] executing: ninja -C build/linux/x64/release install
quickgui> [  +26 ms] ninja: Entering directory `build/linux/x64/release'
quickgui> [+14445 ms] [1/10] Generating /build/source/linux/flutter/ephemeral/libflutter_linux_gtk.so, /build/source/linux/flutter/ephemeral/flutter_linux/fl_basic_message_channel.h, /build/source/linux/flutter/ephemeral/flutter_linux/fl_binary_codec.h, /build/source/linux/flutter/ephemeral/flutter_linux/fl_binary_messenger.h, /build/source/linux/flutter/ephemeral/flutter_linux/fl_dart_project.h, /build/source/linux/flutter/ephemeral/flutter_linux/fl_engine.h, /build/source/linux/flutter/ephemeral/flutter_linux/fl_json_message_codec.h, /build/source/linux/flutter/ephemeral/flutter_linux/fl_json_method_codec.h, /build/source/linux/flutter/ephemeral/flutter_linux/fl_message_codec.h, /build/source/linux/flutter/ephemeral/flutter_linux/fl_method_call.h, /build/source/linux/flutter/ephemeral/flutter_linux/fl_method_channel.h, /build/source/linux/flutter/ephemeral/flutter_linux/fl_method_codec.h, /build/source/linux/flutter/ephemeral/flutter_linux/fl_method_response.h, /build/source/linux/flutter/ephemeral/flutter_linux/fl_plugin_registrar.h, /build/source/linux/flutter/ephemeral/flutter_linux/fl_plugin_registry.h, /build/source/linux/flutter/ephemeral/flutter_linux/fl_standard_message_codec.h, /build/source/linux/flutter/ephemeral/flutter_linux/fl_standard_method_codec.h, /build/source/linux/flutter/ephemeral/flutter_linux/fl_string_codec.h, /build/source/linux/flutter/ephemeral/flutter_linux/fl_value.h, /build/source/linux/flutter/ephemeral/flutter_linux/fl_view.h, /build/source/linux/flutter/ephemeral/flutter_linux/flutter_linux.h, _phony_
quickgui> [   +8 ms] FAILED: /build/source/linux/flutter/ephemeral/libflutter_linux_gtk.so /build/source/linux/flutter/ephemeral/flutter_linux/fl_basic_message_channel.h /build/source/linux/flutter/ephemeral/flutter_linux/fl_binary_codec.h /build/source/linux/flutter/ephemeral/flutter_linux/fl_binary_messenger.h /build/source/linux/flutter/ephemeral/flutter_linux/fl_dart_project.h /build/source/linux/flutter/ephemeral/flutter_linux/fl_engine.h /build/source/linux/flutter/ephemeral/flutter_linux/fl_json_message_codec.h /build/source/linux/flutter/ephemeral/flutter_linux/fl_json_method_codec.h /build/source/linux/flutter/ephemeral/flutter_linux/fl_message_codec.h /build/source/linux/flutter/ephemeral/flutter_linux/fl_method_call.h /build/source/linux/flutter/ephemeral/flutter_linux/fl_method_channel.h /build/source/linux/flutter/ephemeral/flutter_linux/fl_method_codec.h /build/source/linux/flutter/ephemeral/flutter_linux/fl_method_response.h /build/source/linux/flutter/ephemeral/flutter_linux/fl_plugin_registrar.h /build/source/linux/flutter/ephemeral/flutter_linux/fl_plugin_registry.h /build/source/linux/flutter/ephemeral/flutter_linux/fl_standard_message_codec.h /build/source/linux/flutter/ephemeral/flutter_linux/fl_standard_method_codec.h /build/source/linux/flutter/ephemeral/flutter_linux/fl_string_codec.h /build/source/linux/flutter/ephemeral/flutter_linux/fl_value.h /build/source/linux/flutter/ephemeral/flutter_linux/fl_view.h /build/source/linux/flutter/ephemeral/flutter_linux/flutter_linux.h flutter/_phony_ /build/source/build/linux/x64/release/flutter/_phony_ 
quickgui> [        ] cd /build/source/build/linux/x64/release/flutter && /nix/store/irwcgpm8csj7br49jih6kdpqkaqya3vf-cmake-3.30.4/bin/cmake -E env FLUTTER_ROOT=/nix/store/d1ppwlksa636sw80y0flxs2jdyq0yr07-flutter-wrapped-3.24.4-sdk-links PROJECT_DIR=/build/source DART_OBFUSCATION=false SPLIT_DEBUG_INFO=/nix/store/nxxw289lb0j8pb7ax3p9mmx5swzzqp6q-quickgui-1.2.10-debug TRACK_WIDGET_CREATION=true TREE_SHAKE_ICONS=true PACKAGE_CONFIG=/build/source/.dart_tool/package_config.json FLUTTER_TARGET=lib/main.dart /nix/store/d1ppwlksa636sw80y0flxs2jdyq0yr07-flutter-wrapped-3.24.4-sdk-links/packages/flutter_tools/bin/tool_backend.sh linux-x64 Release
quickgui> [        ] [  +10 ms] Failed obtaining PRETTY_NAME for Linux: PathNotFoundException: Cannot open file, path = '/usr/lib/os-release' (OS Error: No such file or directory, errno = 2)
quickgui> [   +1 ms] [  +17 ms] Unable to locate an Android SDK.
quickgui> [        ] [ +137 ms] Initializing file store
quickgui> [        ] [  +18 ms] Skipping target: gen_localizations
quickgui> [        ] [   +4 ms] invalidated build due to missing files: /build/source/.dart_tool/package_config_subset
quickgui> [        ] [   +1 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputMissing: The following inputs were missing: /build/source/.dart_tool/package_config_subset}
quickgui> [        ] [   +7 ms] unpack_linux: Starting due to {}
quickgui> [        ] [ +141 ms] unpack_linux: Complete
quickgui> [        ] [ +208 ms] Found plugin url_launcher_web at /nix/store/02bwaa9svc88fyzbpffxic18475dzghl-pub-url_launcher_web-2.3.1/
quickgui> [        ] [  +20 ms] Found plugin window_size at /nix/store/281pj1qkmwsbzmn02r6q9icaj11x15ab-pub-window_size-0.1.0/plugins/window_size/
quickgui> [        ] [  +22 ms] Found plugin path_provider_linux at /nix/store/4k81c6xlrv9flldg38h9vz71yjynvbnn-pub-path_provider_linux-2.2.1/
quickgui> [        ] [   +9 ms] Found plugin shared_preferences_android at /nix/store/85nhyhivqhdfn8zcp59b4sxcz51nb4ja-pub-shared_preferences_android-2.2.3/
quickgui> [        ] [  +10 ms] Found plugin shared_preferences_foundation at /nix/store/aklaxr0m3qnidlyly2srv8jx4n28b3iz-pub-shared_preferences_foundation-2.4.0/
quickgui> [        ] [  +11 ms] Found plugin url_launcher_ios at /nix/store/c0y1cs8qg8iimamzm0y6g0nn7bz6l8cj-pub-url_launcher_ios-6.3.0/
quickgui> [        ] [  +11 ms] Found plugin flutter_plugin_android_lifecycle at /nix/store/fmpddwahgxhap1444frgg4vkd1nm0ic0-pub-flutter_plugin_android_lifecycle-2.0.20/
quickgui> [        ] [  +10 ms] Found plugin shared_preferences at /nix/store/iawy6vrk3vdj2q32pnqgf6amhp0dk3xh-pub-shared_preferences-2.2.3/
quickgui> [        ] [   +2 ms] Found plugin url_launcher_windows at /nix/store/ivk6fyy4sc5rm6xwq3rr2q3xicr4p5in-pub-url_launcher_windows-3.1.1/
quickgui> [        ] [  +12 ms] Found plugin url_launcher_android at /nix/store/ly3f4fiaspa5n4nak4sh23gxm6wdxr68-pub-url_launcher_android-6.3.3/
quickgui> [        ] [  +12 ms] Found plugin file_picker at /nix/store/nbksgwm99d12hkss1h768rx16jf7gx8h-pub-file_picker-8.0.6/
quickgui> [        ] [   +2 ms] Found plugin url_launcher_macos at /nix/store/nlrr9r5bzb9b1c82lhbx1n26db13ll5k-pub-url_launcher_macos-3.2.0/
quickgui> [        ] [   +3 ms] Found plugin shared_preferences_linux at /nix/store/pa9rc1ak6rpfbw7rnb3hn19385l0m6k5-pub-shared_preferences_linux-2.3.2/
quickgui> [        ] [   +2 ms] Found plugin shared_preferences_windows at /nix/store/qy21qcd19p1wwp1lb1nyj96sy81ag8js-pub-shared_preferences_windows-2.3.2/
quickgui> [        ] [   +7 ms] Found plugin path_provider_windows at /nix/store/wib0w6wj5clkiwglwfiddyiby1ssj6wk-pub-path_provider_windows-2.2.1/
quickgui> [        ] [   +2 ms] Found plugin url_launcher_linux at /nix/store/wrclapn89ya4jlcg654l0qwh6xlbw4l5-pub-url_launcher_linux-3.1.1/
quickgui> [        ] [   +3 ms] Found plugin package_info_plus at /nix/store/xqjqv966371lq9djmlrgmwkrsvf8wjsh-pub-package_info_plus-8.0.0/
quickgui> [        ] [   +5 ms] Found plugin url_launcher at /nix/store/yy83yg70as8yijm6vz1n633vv4fkjcaq-pub-url_launcher-6.3.0/
quickgui> [        ] [   +5 ms] Found plugin shared_preferences_web at /nix/store/zdjfqds2j65c0k1yqjx3dmy6xiqlci9h-pub-shared_preferences_web-2.3.0/
quickgui> [        ] [  +31 ms] gen_dart_plugin_registrant: Complete
quickgui> [        ] [        ] kernel_snapshot_program: Starting due to {}
quickgui> [   +1 ms] [  +10 ms] /nix/store/d1ppwlksa636sw80y0flxs2jdyq0yr07-flutter-wrapped-3.24.4-sdk-links/bin/cache/dart-sdk/bin/dartaotruntime --disable-dart-dev /nix/store/d1ppwlksa636sw80y0flxs2jdyq0yr07-flutter-wrapped-3.24.4-sdk-links/bin/cache/dart-sdk/bin/snapshots/frontend_server_aot.dart.snapshot --sdk-root /nix/store/d1ppwlksa636sw80y0flxs2jdyq0yr07-flutter-wrapped-3.24.4-sdk-links/bin/cache/artifacts/engine/common/flutter_patched_sdk_product/ --target=flutter --no-print-incremental-dependencies -Ddart.vm.profile=false -Ddart.vm.product=true --delete-tostring-package-uri=dart:ui --delete-tostring-package-uri=package:flutter --aot --tfa --target-os linux --packages /build/source/.dart_tool/package_config.json --output-dill /build/source/.dart_tool/flutter_build/039decc5a3fdc4dcd63b4de0ed5383a1/program.dill --depfile /build/source/.dart_tool/flutter_build/039decc5a3fdc4dcd63b4de0ed5383a1/kernel_snapshot_program.d --source file:///build/source/.dart_tool/flutter_build/dart_plugin_registrant.dart --source package:flutter/src/dart_plugin_registrant.dart -Dflutter.dart_plugin_registrant=file:///build/source/.dart_tool/flutter_build/dart_plugin_registrant.dart --verbosity=error package:quickgui/main.dart
quickgui> [        ] [+4813 ms] /nix/store/bgvqb8pa4vspr3abxxyww7fdxqdqwmjr-flutter-sdk-flutter/lib/src/material/color_scheme.dart:1915:39: Error: Method not found: 'SchemeRainbow'.
quickgui> [        ] [   +4 ms]       DynamicSchemeVariant.rainbow => SchemeRainbow(sourceColorHct: sourceColor, isDark: isDark, contrastLevel: contrastLevel),
quickgui> [        ] [        ]                                       ^^^^^^^^^^^^^
quickgui> [        ] [        ] /nix/store/bgvqb8pa4vspr3abxxyww7fdxqdqwmjr-flutter-sdk-flutter/lib/src/material/color_scheme.dart:1916:42: Error: Method not found: 'SchemeFruitSalad'.
quickgui> [        ] [        ]       DynamicSchemeVariant.fruitSalad => SchemeFruitSalad(sourceColorHct: sourceColor, isDark: isDark, contrastLevel: contrastLevel),
quickgui> [        ] [        ]                                          ^^^^^^^^^^^^^^^^
quickgui> [        ] [+8347 ms] Persisting file store
quickgui> [        ] [   +5 ms] Done persisting file store
quickgui> [        ] [   +3 ms] Target kernel_snapshot_program failed: Exception
quickgui> [        ]            #0      KernelSnapshotProgram.build (package:flutter_tools/src/build_system/targets/common.dart:276:7)
quickgui> [        ]            <asynchronous suspension>
quickgui> [        ]            #1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:875:9)
quickgui> [        ]            <asynchronous suspension>
quickgui> [        ]            #2      Future.wait.<anonymous closure> (dart:async/future.dart:534:21)
quickgui> [        ]            <asynchronous suspension>
quickgui> [        ]            #3      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:813:32)
quickgui> [        ]            <asynchronous suspension>
quickgui> [        ]            #4      Future.wait.<anonymous closure> (dart:async/future.dart:534:21)
quickgui> [        ]            <asynchronous suspension>
quickgui> [        ]            #5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:813:32)
quickgui> [        ]            <asynchronous suspension>
quickgui> [        ]            #6      Future.wait.<anonymous closure> (dart:async/future.dart:534:21)
quickgui> [        ]            <asynchronous suspension>
quickgui> [        ]            #7      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:813:32)
quickgui> [        ]            <asynchronous suspension>
quickgui> [        ]            #8      Future.wait.<anonymous closure> (dart:async/future.dart:534:21)
quickgui> [        ]            <asynchronous suspension>
quickgui> [        ]            #9      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:813:32)
quickgui> [        ]            <asynchronous suspension>
quickgui> [        ]            #10     Future.wait.<anonymous closure> (dart:async/future.dart:534:21)
quickgui> [        ]            <asynchronous suspension>
quickgui> [        ]            #11     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:813:32)
quickgui> [        ]            <asynchronous suspension>
quickgui> [   +2 ms]            #12     Future.wait.<anonymous closure> (dart:async/future.dart:534:21)
quickgui> [        ]            <asynchronous suspension>
quickgui> [        ]            #13     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:813:32)
quickgui> [        ]            <asynchronous suspension>
quickgui> [        ]            #14     FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:635:16)
quickgui> [        ]            <asynchronous suspension>
quickgui> [   +3 ms]            #15     AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:328:32)
quickgui> [        ]            <asynchronous suspension>
quickgui> [        ]            #16     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1408:27)
quickgui> [        ]            <asynchronous suspension>
quickgui> [        ]            #17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
quickgui> [        ]            <asynchronous suspension>
quickgui> [        ]            #18     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
quickgui> [        ]            <asynchronous suspension>
quickgui> [        ]            #19     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:416:9)
quickgui> [        ]            <asynchronous suspension>
quickgui> [        ]            #20     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
quickgui> [        ]            <asynchronous suspension>
quickgui> [        ]            #21     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
quickgui> [        ]            <asynchronous suspension>
quickgui> [        ]            #22     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
quickgui> [        ]            <asynchronous suspension>
quickgui> [        ]            #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
quickgui> [        ]            <asynchronous suspension>
quickgui> [        ]            #24     main (package:flutter_tools/executable.dart:93:3)
quickgui> [        ]            <asynchronous suspension>
quickgui> [        ] [   +8 ms] "flutter assemble" took 13,840ms.
quickgui> [        ] [   +3 ms] 
quickgui> [        ]            #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
quickgui> [        ]            #1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:345:7)
quickgui> [        ]            <asynchronous suspension>
quickgui> [        ]            #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1408:27)
quickgui> [        ]            <asynchronous suspension>
quickgui> [        ]            #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
quickgui> [        ]            <asynchronous suspension>
quickgui> [        ]            #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
quickgui> [        ]            <asynchronous suspension>
quickgui> [        ]            #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:416:9)
quickgui> [        ]            <asynchronous suspension>
quickgui> [        ]            #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
quickgui> [        ]            <asynchronous suspension>
quickgui> [        ]            #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
quickgui> [        ]            <asynchronous suspension>
quickgui> [        ]            #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
quickgui> [        ]            <asynchronous suspension>
quickgui> [        ]            #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
quickgui> [        ]            <asynchronous suspension>
quickgui> [        ]            #10     main (package:flutter_tools/executable.dart:93:3)
quickgui> [        ]            <asynchronous suspension>
quickgui> [        ] [        ] Running 1 shutdown hook
quickgui> [        ] [        ] Shutdown hooks complete
quickgui> [        ] [   +2 ms] exiting with code 1
quickgui> [        ] ninja: build stopped: subcommand failed.
quickgui> [  +17 ms] Building Linux application... (completed in 16.6s)
quickgui> [   +1 ms] "flutter linux" took 17,316ms.
quickgui> [   +3 ms] Build process failed
quickgui> [        ] 
quickgui>            #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
quickgui>            #1      _runBuild (package:flutter_tools/src/linux/build_linux.dart:210:5)
quickgui>            <asynchronous suspension>
quickgui>            #2      buildLinux (package:flutter_tools/src/linux/build_linux.dart:83:5)
quickgui>            <asynchronous suspension>
quickgui>            #3      BuildLinuxCommand.runCommand (package:flutter_tools/src/commands/build_linux.dart:87:5)
quickgui>            <asynchronous suspension>
quickgui>            #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1408:27)
quickgui>            <asynchronous suspension>
quickgui>            #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
quickgui>            <asynchronous suspension>
quickgui>            #6      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
quickgui>            <asynchronous suspension>
quickgui>            #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:416:9)
quickgui>            <asynchronous suspension>
quickgui>            #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
quickgui>            <asynchronous suspension>
quickgui>            #9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
quickgui>            <asynchronous suspension>
quickgui>            #10     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
quickgui>            <asynchronous suspension>
quickgui>            #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
quickgui>            <asynchronous suspension>
quickgui>            #12     main (package:flutter_tools/executable.dart:93:3)
quickgui>            <asynchronous suspension>

...

```

**Comment by alioguzhan** [comment]
I can confirm this from NixOS unstable and Kernel 6.12. The exact same error.
