### ISSUE TITLE
Changing directory does not always work and sometimes breaks Quickgui

### ISSUE THREAD

**Issue by philclifford** [quickemu-project/quickgui#54]
While moving around my system looking for somewhere to drop another test VM I notice that attempting to chose `/home/<user>`  and clock on OK left the working directory where it was.

Also, trying to find some reason/pattern to this (in the past the presence of symlinks has had surprising impacts and of course permissions/acls were a likely candidate ) I found I could consistently break quickgui by selecting `/home/<user>/snap/flutter`  (window goes blank/white and loses possibility to do anything if in "Manage Existing" mode, or if in "New" mode bottom half goes white but top half logo is still there and you can "Close" and on return the previous directory will be current ) .  

This may disappear with a reboot as that directory is left over from removing the flutter snap, and is actually a directory  from a zfs dataset bind mounted in to try and cope with the demands of the flutter snap so probably somewhat spurious edge-case.  However, the error message suggests it might be worth "handling"  this  "it cannot happen" event more graciously (i.e. the file picker allows selection of a directory that flutter believes does not exist )

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: FileSystemException: Getting current working directory failed, path = '' (OS Error: No such file or directory, errno = 2)
#0      _Directory.current (dart:io/directory_impl.dart:42)
#1      Directory.current (dart:io/directory.dart:136)
#2      _ManagerState._getVms (package:quickgui/src/pages/manager.dart:133)
#3      _ManagerState.initState.<anonymous closure> (package:quickgui/src/pages/manager.dart:67)
#4      _rootRunUnary (dart:async/zone.dart:1436)
#5      _CustomZone.runUnary (dart:async/zone.dart:1335)
#6      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244)
#7      _CustomZone.bindUnaryCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1281)
#8      _rootRunUnary (dart:async/zone.dart:1444)
#9      _CustomZone.runUnary (dart:async/zone.dart:1335)
#10     _CustomZone.bindUnaryCallback.<anonymous closure> (dart:async/zone.dart:1265)
#11     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:395)
#12     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:426)
#13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192)


```

**Comment by philclifford** [comment]
Further investigation suggests the directory that did not exists was in some kind of snap-remove-related limbo: (because snapd tried to remove it but it was a bind mount so unlink failed on resource busy)

```
drwxr-xr-x 4 phil phil  4.0K Dec 13 10:25 ubuntu-accomplishments
drwxr-xr-x 0 phil phil     2 Dec 13 10:31 flutter    <---
drwxr-xr-x 5 phil phil  4.0K Dec 13 13:27 btop
drwxr-xr-x 5 phil phil  4.0K Dec 14 19:02 openscad
drwxr-xr-x 5 phil phil  4.0K Dec 15 10:33 cura-slicer
```

`rmdir` returns `device or resource busy` and `fuser -v `  indicated kernel mount  ... so unmounted it and then removed it.  Problem 2 resolved (and probably not worth the time to try handling something so odd that should not happen ever)  Should probably let the snapd folks know though.

**Comment by philclifford** [comment]
And the other problem is between seat and keyboard:  slightly counter-intuitive (but consistent) behaviour of the file picker confuses old person who prefers the command line.
Nothing is real.
Strawberry Fields Forever!
