### ISSUE TITLE
Fail to launch quickgui completely

### ISSUE THREAD

**Issue by andy-partington** [quickemu-project/quickgui#63]
I followed your instructions to add your PPA and installed quickgui successfully - my system Kubuntu 21.10  is up to date, when launching from the application launcher I see the following screen.

![image](https://user-images.githubusercontent.com/968384/147423091-3d295516-a447-414a-98f0-164ebdd68bcf.png)

No errors appear, so I tried launching via the terminal and see the following.

```
ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: ProcessException: No such file or directory
  Command: quickget list_csv
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:401)
#1      Process.start (dart:io-patch/process_patch.dart:38)
#2      _runNonInteractiveProcess (dart:io-patch/process_patch.dart:578)
#3      Process.run (dart:io-patch/process_patch.dart:49)
#4      loadOperatingSystems (package:quickgui/main.dart:17)
#5      main (package:quickgui/main.dart:62)
#6      main (file:///home/yannick/quickgui/.dart_tool/flutter_build/generated_main.dart)
#7      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:127)
#8      _rootRun (dart:async/zone.dart:1428)
#9      _CustomZone.run (dart:async/zone.dart:1328)
#10     _runZoned (dart:async/zone.dart:1863)
#11     runZonedGuarded (dart:async/zone.dart:1851)
#12     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:125)
#13     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192)
```
I store quickemu in /home/andy/Projects/quickemu, from there I can run the command `quickget list_csv` and appears to work correctly, I have tried launching quickgui from that directory to see if it picked info from there but same result.

Happy to give any more info required.

**Comment by andy-partington** [comment]
Worked out the issue, was me being stupid. I git cloned quickemu but added your project from the PPA, so when launching your application it didn't know where to find the path to quickemu.
I know this was a me problem, but maybe a message if someone does the same saying "Can't find quickemu in path" maybe if I was more with it I could have got that from no such file or directory.

Will close it anyway.
