### ISSUE TITLE
Empty window on launch

### ISSUE THREAD

**Issue by savchenko** [quickemu-project/quickgui#65]
When running pre-compiled binary:

![image](https://user-images.githubusercontent.com/300146/149603489-228bf434-d4f7-4e93-b8e3-2cd7d669f940.png)

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: ProcessException: No such file or directory
  Command: quickget list_csv
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:401)
#1      Process.start (dart:io-patch/process_patch.dart:38)
#2      _runNonInteractiveProcess (dart:io-patch/process_patch.dart:578)
#3      Process.run (dart:io-patch/process_patch.dart:49)
#4      loadOperatingSystems (package:quickgui/main.dart:17)
#5      main (package:quickgui/main.dart:62)
#6      main (file:///home/yannick/quickgui/.dart_tool/flutter_build/generated_main.dart)
#7      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:127)
#8      _rootRun (dart:async/zone.dart:1428)
#9      _CustomZone.run (dart:async/zone.dart:1328)
#10     _runZoned (dart:async/zone.dart:1863)
#11     runZonedGuarded (dart:async/zone.dart:1851)
#12     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:125)
#13     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192)
```

```
$ flutter --version
Flutter 2.8.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 77d935af4d (4 weeks ago) • 2021-12-16 08:37:33 -0800
Engine • revision 890a5fca2e
Tools • Dart 2.15.1
```

Same result when building from `master`.

**Comment by savchenko** [comment]
It was an issue with `$PATH`, fixed.
