### ISSUE TITLE
Empty window on launch

### ISSUE THREAD

**Issue by VieuxSio** [quickemu-project/quickgui#71]
Hi, 
I have an issue when launching quickgui. I verify than quickget and quickemu are in the current path, they are. 
I obtain an empty window when launching and this error message on console : 

`[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel dev.fluttercommunity.plus/package_info)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:175)
<asynchronous suspension>
#1      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:377)
<asynchronous suspension>
#2      MethodChannelPackageInfo.getAll (package:package_info_plus_platform_interface/method_channel_package_info.dart:13)
<asynchronous suspension>
#3      PackageInfo.fromPlatform (package:package_info_plus/package_info_plus.dart:36)
<asynchronous suspension>
#4      main (package:quickgui/main.dart:62)
<asynchronous suspension>`

I'm not sure that I can solve it myself.
Regards

**Comment by PloniAlmoni** [comment]
I can confirm this issue.

**Comment by sgnh** [comment]
It's a broken dependency:
https://github.com/fluttercommunity/plus_plugins/issues/773

It looks like they already fixed it so it might just be a matter of time before this works again without any change. But for now, the easiest solution is to change line 46 in pubspec.yaml from:
`  package_info_plus: ^1.3.0`
to
`  package_info_plus: 1.3.0`

**Comment by flexiondotorg** [comment]
Duplicate of #68
